config/routes.rb
Rails.application.routes.draw do

  get "profiles" => "profiles#index"
  get 'profiles/:id' => 'profiles#show', as: :profile

  resources :tweets do
      resource :like
  end

  resources :relationships

  root 'tweets#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :user
  belongs_to :friend, class_name: "User"

  # Create an association to friend
# provide a class_name of "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  validates :message, presence: true, length: { maximum: 140, too_long: "A tweet is only 140 characters! Everyone knows that!"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :relationships
  has_many :friends, through: :relationships

  has_many :inverse_relationships, class_name: 'Relationship', foreign_key: 'friend_id'
  has_many :inverse_friends, through: :inverse_relationships, source: :user
  has_many :likes

  validates :username, presence: true, uniqueness: true

  def likes?(tweet)
    tweet.likes.where(user_id: self.id).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :bio, :location, :email, :password, :password_confirmation])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :bio, :location, :email, :password, :password_confirmation])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_tweet, :authenticate_user!

  def create
    @tweet.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to request.referrer}
    end
  end

  def destroy
    @tweet.likes.where(user_id: current_user.id).destroy_all
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  # In the show action...
  # lookup a specific user (based on their ID)
  # assign that object to the @user instance variable

  def show
    @user = User.find(params[:id]) 
  end

  def index
    @users = User.all
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @relationship = current_user.relationships.build(friend_id: params[:friend_id])

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to profile_path(current_user.id), notice: "User followed!"}
      else
        format.html {redirect_to root_path, error: "Unable to follow user" }
      end
    end
  end

  def destroy
    @relationship = current_user.relationships.find(params[:id])
    @relationship.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(current_user.id), notice: "User unfollowed"}
    end
  end

  private

  def relationship_params
    params.require(:relationship).permit(:user_id, :friend_id)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :set_tweet, only: [:edit, :update, :show, :destroy]

  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_path(@tweet.id), notice: 'success!'}
      else
        format.html { render :new, error: @tweet.errors[:messavge] }
      end
    end
  end

  def edit
  end

  def show
  end

  def update

    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_path(@tweet.id), notice: "success"}
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Tweet was deleted'}
    end
  end

 private

 def set_tweet
   @tweet = Tweet.find(params[:id])
 end

 def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bark</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<h1>Select a User</h1>

<% @users.each do |user|  %>
  <%= link_to user.username, profile_path(user.id) %><br>
<% end %>

app/views/profiles/show.html.erb
<div class="row">
  <div class= "col-xs-4">
  <h3><%= @user.name %></h3>
  <h5><%= @user.username %></h5>
  <h5><p><%= @user.bio %></p></h5>
  <h5><%= @user.location %></h5>
  <h5>Joined on <%= @user.created_at.strftime("%B %Y") %></h5>

  <%= @user.relationships.count %> Following
  <br />
  <% @user.relationships.each do |relationship| %>
    <%=link_to relationship.friend.name, profile_path(relationship.friend) %>
  <%end%>
  <br />
  <br />
  <%= pluralize(@user.inverse_relationships.count, "Follower") %>.
  <br />
  <% @user.inverse_friends.each do |friend| %>
    <%=link_to friend.name, profile_path(friend) %> <br />
  <%end%>
  </div>

  <div class= "col-xs-7">
    <div class="panel panel-default">
      <% @user.tweets.each do |tweet| %>
        <div class="panel-body">
        <strong><%= tweet.user.username %> </strong><small>tweeted <%= time_ago_in_words(tweet.created_at) %> ago</small>
        <br />
        <br />
        <%= tweet.message %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<br />

<% if current_user.id != @user.id %>
  <% if current_user.friends.include?(@user) %>
    <%= link_to 'Unfollow', relationship_path(current_user.relationships.find_by_friend_id(@user.id)), method: :delete, class: "btn btn-danger"%>
  <% else %>
    <%= link_to "Follow", relationships_path(friend_id: @user.id), method: :post, class: 'btn btn-success' %>
  <% end %>
<% end %>

app/views/shared/_likes.html.erb
<% if current_user.likes?(@tweet) %>
  <%= link_to "Unlike", tweet_like_path(@tweet.id), method: :delete, class: "btn btn-danger"%>
<% else %>
  <%= link_to "Like", tweet_like_path(@tweet.id), method: :post, class: 'btn btn-success' %>
<% end %>

<p class="">
  <%= @tweet.likes.count %> likes!
</p>

<h5>Liked By:</h5>
<% @tweet.likes.each do |like| %>
  <%= like.user.username %>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
<% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% @tweet.errors.each do |attribute, message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id, readonly: true %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <p class="post-as"> barking as: <span><%= current_user.username %></span></p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= render 'form' %>
<%= link_to 'Show', tweet_path(@tweet.id) %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Whatever, this is just a header</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.user.username %></td>
        <td><%= link_to 'Show', tweet_path(tweet.id) %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet.id) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Tweet', new_tweet_path, class: 'btn btn-primary' %>
<%= link_to 'Sign Out!', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user.username %>
</p>

<%= render 'shared/likes' %><br>
<%= link_to 'Edit', edit_tweet_path(@tweet.id) %> |
<%= link_to 'Back', tweets_path %>